<!-- Para praticar os métodos aprendidos no decorrer dessa aula e também aprender novos, vamos realizar alguns tratamentos e seleções utilizando um arquivo csv diferente: alunos.csv.

Esse arquivo é o mesmo utilizado para resolução dos desafios da aula 1 e 3 e possui dados referentes a alunos de um curso superior. Com base nisso, solucione os problemas propostos abaixo utilizando os conhecimentos adquiridos até aqui. -->

<!-- 1) Os alunos participaram de uma atividade extracurricular e ganharam pontos extras. Esses pontos extras correspondem a 40% da nota atual de cada um deles. Com base nisso, crie uma coluna chamada "Pontos_extras" que contenha os pontos extras de cada aluno, ou seja, 40% da nota atual deles. -->

In [15]:
import pandas as pd

df = pd.read_csv('dados/Alunos2.csv')

df.head()

    Nome  Idade  Notas  Aprovado
0    Ary     20    7.5      True
1    Ana     18    NaN     False
2  Cátia     27    2.5     False
3  Denis     18    5.0     False
4   Beto     21   10.0      True

In [19]:
df['Pontos_Extras'] = df['Notas'] * 0.4
df.head()

    Nome  Idade  Notas  Aprovado  Pontos_Extras
0    Ary     20    7.5      True            3.0
1    Ana     18    NaN     False            NaN
2  Cátia     27    2.5     False            1.0
3  Denis     18    5.0     False            2.0
4   Beto     21   10.0      True            4.0

In [17]:
# 2) Crie mais uma coluna, chamada "Notas_finais" que possua as notas de cada aluno somada com os pontos extras.

In [25]:
df['Notas_finais'] = df['Notas'] + df['Pontos_Extras']
df

,Nome,Idade,Notas,Aprovado,Pontos_Extras,Notas_finais,Aprovado_final
0,Ary,20,7.5,True,3.00,10.50,Sim
1,Ana,18,NaN,False,NaN,NaN,Não
2,Cátia,27,2.5,False,1.00,3.50,Não
3,Denis,18,5.0,False,2.00,7.00,Não
4,Beto,21,10.0,True,4.00,14.00,Sim
5,Bruna,23,NaN,False,NaN,NaN,Não
6,Dara,21,7.0,True,2.80,9.80,Sim
7,Carlos,19,6.0,True,2.40,8.40,Sim
8,Alice,35,5.6,False,2.24,7.84,Não
9,Vitor,28,NaN,False,NaN,NaN,Não
10,Daniel,21,NaN,False,NaN,NaN,Não
11,Igor,24,4.5,False,1.80,6.30,Não
12,Sthefanie,26,9.5,True,3.80,13.30,Sim
13,Mirla,25,9.0,True,3.60,12.60,Sim
14,Paulo,37,NaN,False,NaN,NaN,Não
15,Mylena,29,7.0,True,2.80,9.80,Sim
16,Lucas,33,NaN,False,NaN,NaN,Não
17,Nadia,34,8.0,True,3.20,11.20,Sim

In [ ]:
# 3) Como houve uma pontuação extra, alguns alunos que não tinham sido 
# aprovados antes podem ter sido aprovados agora. Com base nisso, crie uma coluna 
# chamada "Aprovado_final" com os seguintes valores:

# True: caso o aluno esteja aprovado (nota final deve ser maior ou igual a 6);
# False: caso o aluno esteja reprovado (nota final deve ser menor que 6).

<!-- 2) Crie mais uma coluna, chamada "Notas_finais" que possua as notas de cada aluno somada com os pontos extras. -->

<!-- 3) Como houve uma pontuação extra, alguns alunos que não tinham sido aprovados antes podem ter sido aprovados agora. Com base nisso, crie uma coluna chamada "Aprovado_final" com os seguintes valores:

True: caso o aluno esteja aprovado (nota final deve ser maior ou igual a 6);
False: caso o aluno esteja reprovado (nota final deve ser menor que 6). -->

In [26]:
df['Aprovado_final'] = \
df['Notas_finais'].apply(lambda x: "Sim" if x >= 6 else "Não") 

df

,Nome,Idade,Notas,Aprovado,Pontos_Extras,Notas_finais,Aprovado_final
0,Ary,20,7.5,True,3.00,10.50,Sim
1,Ana,18,NaN,False,NaN,NaN,Não
2,Cátia,27,2.5,False,1.00,3.50,Não
3,Denis,18,5.0,False,2.00,7.00,Sim
4,Beto,21,10.0,True,4.00,14.00,Sim
5,Bruna,23,NaN,False,NaN,NaN,Não
6,Dara,21,7.0,True,2.80,9.80,Sim
7,Carlos,19,6.0,True,2.40,8.40,Sim
8,Alice,35,5.6,False,2.24,7.84,Sim
9,Vitor,28,NaN,False,NaN,NaN,Não
10,Daniel,21,NaN,False,NaN,NaN,Não
11,Igor,24,4.5,False,1.80,6.30,Sim
12,Sthefanie,26,9.5,True,3.80,13.30,Sim
13,Mirla,25,9.0,True,3.60,12.60,Sim
14,Paulo,37,NaN,False,NaN,NaN,Não
15,Mylena,29,7.0,True,2.80,9.80,Sim
16,Lucas,33,NaN,False,NaN,NaN,Não
17,Nadia,34,8.0,True,3.20,11.20,Sim

<!-- 4) Faça uma seleção e verifique quais alunos não tinham sido aprovados anteriormente, mas foram aprovados após a soma dos pontos extras. -->